version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-38
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./../.env
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"

  migrations:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./../.env
    command: >
      sh -c "python manage.py migrate"

  db:
    image: postgres:15.2
    restart: always
    env_file:
      - ./../.env
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 15

volumes:
  db_data: